/**
 * Xillio Engine
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.xillio.engine.handler/ApiClient', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ContainerDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/CreatedDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/Decorators', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/DescriptionDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/Entity', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/EntityResponse', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ErrorResponse', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/FileDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/FileSystemDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/HashDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/MimeTypeDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ModifiedDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/NameDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ParentDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/PreviewDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/PropertiesDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/VersionDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.api/AllApi', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.api/ContentApi', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.api/EntityApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./com.sphereon.sdk.xillio.engine.model/ContainerDecorator'), require('./com.sphereon.sdk.xillio.engine.model/CreatedDecorator'), require('./com.sphereon.sdk.xillio.engine.model/Decorators'), require('./com.sphereon.sdk.xillio.engine.model/DescriptionDecorator'), require('./com.sphereon.sdk.xillio.engine.model/Entity'), require('./com.sphereon.sdk.xillio.engine.model/EntityResponse'), require('./com.sphereon.sdk.xillio.engine.model/ErrorResponse'), require('./com.sphereon.sdk.xillio.engine.model/FileDecorator'), require('./com.sphereon.sdk.xillio.engine.model/FileSystemDecorator'), require('./com.sphereon.sdk.xillio.engine.model/HashDecorator'), require('./com.sphereon.sdk.xillio.engine.model/MimeTypeDecorator'), require('./com.sphereon.sdk.xillio.engine.model/ModifiedDecorator'), require('./com.sphereon.sdk.xillio.engine.model/NameDecorator'), require('./com.sphereon.sdk.xillio.engine.model/ParentDecorator'), require('./com.sphereon.sdk.xillio.engine.model/PreviewDecorator'), require('./com.sphereon.sdk.xillio.engine.model/PropertiesDecorator'), require('./com.sphereon.sdk.xillio.engine.model/VersionDecorator'), require('./com.sphereon.sdk.xillio.engine.api/AllApi'), require('./com.sphereon.sdk.xillio.engine.api/ContentApi'), require('./com.sphereon.sdk.xillio.engine.api/EntityApi'));
  }
}(function(ApiClient, ContainerDecorator, CreatedDecorator, Decorators, DescriptionDecorator, Entity, EntityResponse, ErrorResponse, FileDecorator, FileSystemDecorator, HashDecorator, MimeTypeDecorator, ModifiedDecorator, NameDecorator, ParentDecorator, PreviewDecorator, PropertiesDecorator, VersionDecorator, AllApi, ContentApi, EntityApi) {
  'use strict';

  /**
   * Xillio Engine Javascript SDK.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var xillio-engine = require('com.sphereon.sdk.xillio.engine.handler/index'); // See note below*.
   * var xxxSvc = new xillio-engine.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new xillio-engine.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['com.sphereon.sdk.xillio.engine.handler/index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new xillio-engine.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new xillio-engine.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module com.sphereon.sdk.xillio.engine.handler/index
   * @version 0.1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ContainerDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ContainerDecorator}
     */
    ContainerDecorator: ContainerDecorator,
    /**
     * The CreatedDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/CreatedDecorator}
     */
    CreatedDecorator: CreatedDecorator,
    /**
     * The Decorators model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/Decorators}
     */
    Decorators: Decorators,
    /**
     * The DescriptionDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/DescriptionDecorator}
     */
    DescriptionDecorator: DescriptionDecorator,
    /**
     * The Entity model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/Entity}
     */
    Entity: Entity,
    /**
     * The EntityResponse model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/EntityResponse}
     */
    EntityResponse: EntityResponse,
    /**
     * The ErrorResponse model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The FileDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/FileDecorator}
     */
    FileDecorator: FileDecorator,
    /**
     * The FileSystemDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/FileSystemDecorator}
     */
    FileSystemDecorator: FileSystemDecorator,
    /**
     * The HashDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/HashDecorator}
     */
    HashDecorator: HashDecorator,
    /**
     * The MimeTypeDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/MimeTypeDecorator}
     */
    MimeTypeDecorator: MimeTypeDecorator,
    /**
     * The ModifiedDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ModifiedDecorator}
     */
    ModifiedDecorator: ModifiedDecorator,
    /**
     * The NameDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/NameDecorator}
     */
    NameDecorator: NameDecorator,
    /**
     * The ParentDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ParentDecorator}
     */
    ParentDecorator: ParentDecorator,
    /**
     * The PreviewDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/PreviewDecorator}
     */
    PreviewDecorator: PreviewDecorator,
    /**
     * The PropertiesDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/PropertiesDecorator}
     */
    PropertiesDecorator: PropertiesDecorator,
    /**
     * The VersionDecorator model constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/VersionDecorator}
     */
    VersionDecorator: VersionDecorator,
    /**
     * The AllApi service constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.api/AllApi}
     */
    AllApi: AllApi,
    /**
     * The ContentApi service constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.api/ContentApi}
     */
    ContentApi: ContentApi,
    /**
     * The EntityApi service constructor.
     * @property {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.api/EntityApi}
     */
    EntityApi: EntityApi
  };

  return exports;
}));
