/**
 * Xillio Engine
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['com.sphereon.sdk.xillio.engine.handler/ApiClient', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ContainerDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/CreatedDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/DescriptionDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/FileDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/FileSystemDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/HashDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/MimeTypeDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ModifiedDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/NameDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ParentDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/PreviewDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/PropertiesDecorator', 'com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/VersionDecorator'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ContainerDecorator'), require('./CreatedDecorator'), require('./DescriptionDecorator'), require('./FileDecorator'), require('./FileSystemDecorator'), require('./HashDecorator'), require('./MimeTypeDecorator'), require('./ModifiedDecorator'), require('./NameDecorator'), require('./ParentDecorator'), require('./PreviewDecorator'), require('./PropertiesDecorator'), require('./VersionDecorator'));
  } else {
    // Browser globals (root is window)
    if (!root.xillio-engine) {
      root.xillio-engine = {};
    }
    root.xillio-engine.Decorators = factory(root.xillio-engine.ApiClient, root.xillio-engine.ContainerDecorator, root.xillio-engine.CreatedDecorator, root.xillio-engine.DescriptionDecorator, root.xillio-engine.FileDecorator, root.xillio-engine.FileSystemDecorator, root.xillio-engine.HashDecorator, root.xillio-engine.MimeTypeDecorator, root.xillio-engine.ModifiedDecorator, root.xillio-engine.NameDecorator, root.xillio-engine.ParentDecorator, root.xillio-engine.PreviewDecorator, root.xillio-engine.PropertiesDecorator, root.xillio-engine.VersionDecorator);
  }
}(this, function(ApiClient, ContainerDecorator, CreatedDecorator, DescriptionDecorator, FileDecorator, FileSystemDecorator, HashDecorator, MimeTypeDecorator, ModifiedDecorator, NameDecorator, ParentDecorator, PreviewDecorator, PropertiesDecorator, VersionDecorator) {
  'use strict';




  /**
   * The Decorators model module.
   * @module com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/Decorators
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Decorators</code>.
   * @alias module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/Decorators
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>Decorators</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/Decorators} obj Optional instance to populate.
   * @return {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/Decorators} The populated <code>Decorators</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('container')) {
        obj['container'] = ContainerDecorator.constructFromObject(data['container']);
      }
      if (data.hasOwnProperty('created')) {
        obj['created'] = CreatedDecorator.constructFromObject(data['created']);
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = DescriptionDecorator.constructFromObject(data['description']);
      }
      if (data.hasOwnProperty('file')) {
        obj['file'] = FileDecorator.constructFromObject(data['file']);
      }
      if (data.hasOwnProperty('filesystem')) {
        obj['filesystem'] = FileSystemDecorator.constructFromObject(data['filesystem']);
      }
      if (data.hasOwnProperty('hash')) {
        obj['hash'] = HashDecorator.constructFromObject(data['hash']);
      }
      if (data.hasOwnProperty('mimeType')) {
        obj['mimeType'] = MimeTypeDecorator.constructFromObject(data['mimeType']);
      }
      if (data.hasOwnProperty('modified')) {
        obj['modified'] = ModifiedDecorator.constructFromObject(data['modified']);
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = NameDecorator.constructFromObject(data['name']);
      }
      if (data.hasOwnProperty('parent')) {
        obj['parent'] = ParentDecorator.constructFromObject(data['parent']);
      }
      if (data.hasOwnProperty('preview')) {
        obj['preview'] = PreviewDecorator.constructFromObject(data['preview']);
      }
      if (data.hasOwnProperty('properties')) {
        obj['properties'] = PropertiesDecorator.constructFromObject(data['properties']);
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = VersionDecorator.constructFromObject(data['version']);
      }
    }
    return obj;
  }

  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ContainerDecorator} container
   */
  exports.prototype['container'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/CreatedDecorator} created
   */
  exports.prototype['created'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/DescriptionDecorator} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/FileDecorator} file
   */
  exports.prototype['file'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/FileSystemDecorator} filesystem
   */
  exports.prototype['filesystem'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/HashDecorator} hash
   */
  exports.prototype['hash'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/MimeTypeDecorator} mimeType
   */
  exports.prototype['mimeType'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ModifiedDecorator} modified
   */
  exports.prototype['modified'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/NameDecorator} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/ParentDecorator} parent
   */
  exports.prototype['parent'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/PreviewDecorator} preview
   */
  exports.prototype['preview'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/PropertiesDecorator} properties
   */
  exports.prototype['properties'] = undefined;
  /**
   * @member {module:com.sphereon.sdk.xillio.engine.handler/com.sphereon.sdk.xillio.engine.model/VersionDecorator} version
   */
  exports.prototype['version'] = undefined;



  return exports;
}));


