/* 
 * Xillio Engine
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Sphereon.SDK.Xillio.Engine.Client;
using Sphereon.SDK.Xillio.Engine.Model;

namespace Sphereon.SDK.Xillio.Engine.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IContentApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Download an Entity\&quot;s Binary Content
        /// </summary>
        /// <remarks>
        /// Download an Entity\&quot;s Binary Content
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GetContent (string configurationId, string path);

        /// <summary>
        /// Download an Entity\&quot;s Binary Content
        /// </summary>
        /// <remarks>
        /// Download an Entity\&quot;s Binary Content
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GetContentWithHttpInfo (string configurationId, string path);
        /// <summary>
        /// Replaces an Entity\&quot;s Binary Content
        /// </summary>
        /// <remarks>
        /// Replaces an Entity\&quot;s Binary Content
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns></returns>
        void UpdateContent (string configurationId, string path);

        /// <summary>
        /// Replaces an Entity\&quot;s Binary Content
        /// </summary>
        /// <remarks>
        /// Replaces an Entity\&quot;s Binary Content
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UpdateContentWithHttpInfo (string configurationId, string path);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Download an Entity\&quot;s Binary Content
        /// </summary>
        /// <remarks>
        /// Download an Entity\&quot;s Binary Content
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GetContentAsync (string configurationId, string path);

        /// <summary>
        /// Download an Entity\&quot;s Binary Content
        /// </summary>
        /// <remarks>
        /// Download an Entity\&quot;s Binary Content
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetContentAsyncWithHttpInfo (string configurationId, string path);
        /// <summary>
        /// Replaces an Entity\&quot;s Binary Content
        /// </summary>
        /// <remarks>
        /// Replaces an Entity\&quot;s Binary Content
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UpdateContentAsync (string configurationId, string path);

        /// <summary>
        /// Replaces an Entity\&quot;s Binary Content
        /// </summary>
        /// <remarks>
        /// Replaces an Entity\&quot;s Binary Content
        /// </remarks>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UpdateContentAsyncWithHttpInfo (string configurationId, string path);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ContentApi : IContentApi
    {
        private Sphereon.SDK.Xillio.Engine.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ContentApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Sphereon.SDK.Xillio.Engine.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ContentApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ContentApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Sphereon.SDK.Xillio.Engine.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Sphereon.SDK.Xillio.Engine.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Download an Entity\&quot;s Binary Content Download an Entity\&quot;s Binary Content
        /// </summary>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GetContent (string configurationId, string path)
        {
             ApiResponse<System.IO.Stream> localVarResponse = GetContentWithHttpInfo(configurationId, path);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Download an Entity\&quot;s Binary Content Download an Entity\&quot;s Binary Content
        /// </summary>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public ApiResponse< System.IO.Stream > GetContentWithHttpInfo (string configurationId, string path)
        {
            // verify the required parameter 'configurationId' is set
            if (configurationId == null)
                throw new ApiException(400, "Missing required parameter 'configurationId' when calling ContentApi->GetContent");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling ContentApi->GetContent");

            var localVarPath = "/contents/{configurationId}/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (configurationId != null) localVarPathParams.Add("configurationId", Configuration.ApiClient.ParameterToString(configurationId)); // path parameter
            if (path != null) localVarPathParams.Add("path", Configuration.ApiClient.ParameterToString(path)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
            
        }

        /// <summary>
        /// Download an Entity\&quot;s Binary Content Download an Entity\&quot;s Binary Content
        /// </summary>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GetContentAsync (string configurationId, string path)
        {
             ApiResponse<System.IO.Stream> localVarResponse = await GetContentAsyncWithHttpInfo(configurationId, path);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Download an Entity\&quot;s Binary Content Download an Entity\&quot;s Binary Content
        /// </summary>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GetContentAsyncWithHttpInfo (string configurationId, string path)
        {
            // verify the required parameter 'configurationId' is set
            if (configurationId == null)
                throw new ApiException(400, "Missing required parameter 'configurationId' when calling ContentApi->GetContent");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling ContentApi->GetContent");

            var localVarPath = "/contents/{configurationId}/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/octet-stream"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (configurationId != null) localVarPathParams.Add("configurationId", Configuration.ApiClient.ParameterToString(configurationId)); // path parameter
            if (path != null) localVarPathParams.Add("path", Configuration.ApiClient.ParameterToString(path)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetContent", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<System.IO.Stream>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (System.IO.Stream) Configuration.ApiClient.Deserialize(localVarResponse, typeof(System.IO.Stream)));
            
        }

        /// <summary>
        /// Replaces an Entity\&quot;s Binary Content Replaces an Entity\&quot;s Binary Content
        /// </summary>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns></returns>
        public void UpdateContent (string configurationId, string path)
        {
             UpdateContentWithHttpInfo(configurationId, path);
        }

        /// <summary>
        /// Replaces an Entity\&quot;s Binary Content Replaces an Entity\&quot;s Binary Content
        /// </summary>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> UpdateContentWithHttpInfo (string configurationId, string path)
        {
            // verify the required parameter 'configurationId' is set
            if (configurationId == null)
                throw new ApiException(400, "Missing required parameter 'configurationId' when calling ContentApi->UpdateContent");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling ContentApi->UpdateContent");

            var localVarPath = "/contents/{configurationId}/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/octet-stream"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (configurationId != null) localVarPathParams.Add("configurationId", Configuration.ApiClient.ParameterToString(configurationId)); // path parameter
            if (path != null) localVarPathParams.Add("path", Configuration.ApiClient.ParameterToString(path)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateContent", localVarResponse);
                if (exception != null) throw exception;
            }

            
            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Replaces an Entity\&quot;s Binary Content Replaces an Entity\&quot;s Binary Content
        /// </summary>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UpdateContentAsync (string configurationId, string path)
        {
             await UpdateContentAsyncWithHttpInfo(configurationId, path);

        }

        /// <summary>
        /// Replaces an Entity\&quot;s Binary Content Replaces an Entity\&quot;s Binary Content
        /// </summary>
        /// <exception cref="Sphereon.SDK.Xillio.Engine.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="configurationId">The id of a configured repository.</param>
        /// <param name="path">The XDIP path to the entity.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> UpdateContentAsyncWithHttpInfo (string configurationId, string path)
        {
            // verify the required parameter 'configurationId' is set
            if (configurationId == null)
                throw new ApiException(400, "Missing required parameter 'configurationId' when calling ContentApi->UpdateContent");
            // verify the required parameter 'path' is set
            if (path == null)
                throw new ApiException(400, "Missing required parameter 'path' when calling ContentApi->UpdateContent");

            var localVarPath = "/contents/{configurationId}/{path}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/octet-stream"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (configurationId != null) localVarPathParams.Add("configurationId", Configuration.ApiClient.ParameterToString(configurationId)); // path parameter
            if (path != null) localVarPathParams.Add("path", Configuration.ApiClient.ParameterToString(path)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateContent", localVarResponse);
                if (exception != null) throw exception;
            }

            
            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
