/* 
 * Xillio Engine
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Sphereon.SDK.Xillio.Engine.Model
{
    /// <summary>
    /// The description decorator provides a small excerpt or description for an entity. This is generally used as a preview message or subtitle.
    /// </summary>
    [DataContract]
    public partial class DescriptionDecorator :  IEquatable<DescriptionDecorator>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionDecorator" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DescriptionDecorator() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DescriptionDecorator" /> class.
        /// </summary>
        /// <param name="_Short">A short extract or subtitle of the entity. (required).</param>
        public DescriptionDecorator(string _Short = null)
        {
            // to ensure "_Short" is required (not null)
            if (_Short == null)
            {
                throw new InvalidDataException("_Short is a required property for DescriptionDecorator and cannot be null");
            }
            else
            {
                this._Short = _Short;
            }
        }
        
        /// <summary>
        /// A short extract or subtitle of the entity.
        /// </summary>
        /// <value>A short extract or subtitle of the entity.</value>
        [DataMember(Name="short", EmitDefaultValue=false)]
        public string _Short { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DescriptionDecorator {\n");
            sb.Append("  _Short: ").Append(_Short).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DescriptionDecorator);
        }

        /// <summary>
        /// Returns true if DescriptionDecorator instances are equal
        /// </summary>
        /// <param name="other">Instance of DescriptionDecorator to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DescriptionDecorator other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._Short == other._Short ||
                    this._Short != null &&
                    this._Short.Equals(other._Short)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._Short != null)
                    hash = hash * 59 + this._Short.GetHashCode();
                return hash;
            }
        }
    }

}
