/* 
 * Xillio Engine
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Sphereon.SDK.Xillio.Engine.Model
{
    /// <summary>
    /// The modified decorator signifies when an entity was last modified.
    /// </summary>
    [DataContract]
    public partial class ModifiedDecorator :  IEquatable<ModifiedDecorator>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifiedDecorator" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModifiedDecorator() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModifiedDecorator" /> class.
        /// </summary>
        /// <param name="Date">The last modification date of the entity. (required).</param>
        /// <param name="By">The name of the user or entity that last modified this entity..</param>
        public ModifiedDecorator(DateTime? Date = null, string By = null)
        {
            // to ensure "Date" is required (not null)
            if (Date == null)
            {
                throw new InvalidDataException("Date is a required property for ModifiedDecorator and cannot be null");
            }
            else
            {
                this.Date = Date;
            }
            this.By = By;
        }
        
        /// <summary>
        /// The last modification date of the entity.
        /// </summary>
        /// <value>The last modification date of the entity.</value>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public DateTime? Date { get; set; }
        /// <summary>
        /// The name of the user or entity that last modified this entity.
        /// </summary>
        /// <value>The name of the user or entity that last modified this entity.</value>
        [DataMember(Name="by", EmitDefaultValue=false)]
        public string By { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModifiedDecorator {\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  By: ").Append(By).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ModifiedDecorator);
        }

        /// <summary>
        /// Returns true if ModifiedDecorator instances are equal
        /// </summary>
        /// <param name="other">Instance of ModifiedDecorator to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModifiedDecorator other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Date == other.Date ||
                    this.Date != null &&
                    this.Date.Equals(other.Date)
                ) && 
                (
                    this.By == other.By ||
                    this.By != null &&
                    this.By.Equals(other.By)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Date != null)
                    hash = hash * 59 + this.Date.GetHashCode();
                if (this.By != null)
                    hash = hash * 59 + this.By.GetHashCode();
                return hash;
            }
        }
    }

}
