/* 
 * Xillio Engine
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Sphereon.SDK.Xillio.Engine.Model
{
    /// <summary>
    /// The name decorator represents both a technical name and a human readable name for an entity. This could be anything from the title of a web page to the filename of a document.
    /// </summary>
    [DataContract]
    public partial class NameDecorator :  IEquatable<NameDecorator>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NameDecorator" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected NameDecorator() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="NameDecorator" /> class.
        /// </summary>
        /// <param name="DisplayName">The human readable name of the entity. (required).</param>
        /// <param name="SystemName">The technical name of the entity. (required).</param>
        public NameDecorator(string DisplayName = null, string SystemName = null)
        {
            // to ensure "DisplayName" is required (not null)
            if (DisplayName == null)
            {
                throw new InvalidDataException("DisplayName is a required property for NameDecorator and cannot be null");
            }
            else
            {
                this.DisplayName = DisplayName;
            }
            // to ensure "SystemName" is required (not null)
            if (SystemName == null)
            {
                throw new InvalidDataException("SystemName is a required property for NameDecorator and cannot be null");
            }
            else
            {
                this.SystemName = SystemName;
            }
        }
        
        /// <summary>
        /// The human readable name of the entity.
        /// </summary>
        /// <value>The human readable name of the entity.</value>
        [DataMember(Name="displayName", EmitDefaultValue=false)]
        public string DisplayName { get; set; }
        /// <summary>
        /// The technical name of the entity.
        /// </summary>
        /// <value>The technical name of the entity.</value>
        [DataMember(Name="systemName", EmitDefaultValue=false)]
        public string SystemName { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NameDecorator {\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  SystemName: ").Append(SystemName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as NameDecorator);
        }

        /// <summary>
        /// Returns true if NameDecorator instances are equal
        /// </summary>
        /// <param name="other">Instance of NameDecorator to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NameDecorator other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.DisplayName == other.DisplayName ||
                    this.DisplayName != null &&
                    this.DisplayName.Equals(other.DisplayName)
                ) && 
                (
                    this.SystemName == other.SystemName ||
                    this.SystemName != null &&
                    this.SystemName.Equals(other.SystemName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.DisplayName != null)
                    hash = hash * 59 + this.DisplayName.GetHashCode();
                if (this.SystemName != null)
                    hash = hash * 59 + this.SystemName.GetHashCode();
                return hash;
            }
        }
    }

}
