/* 
 * Xillio Engine
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Xillio.Engine.Api;
using Sphereon.SDK.Xillio.Engine.Model;
using Sphereon.SDK.Xillio.Engine.Client;
using System.Reflection;

namespace Sphereon.SDK.Xillio.Engine.Test
{
    /// <summary>
    ///  Class for testing Decorators
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DecoratorsTests
    {
        // TODO uncomment below to declare an instance variable for Decorators
        //private Decorators instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Decorators
            //instance = new Decorators();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Decorators
        /// </summary>
        [Test]
        public void DecoratorsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Decorators
            //Assert.IsInstanceOfType<Decorators> (instance, "variable 'instance' is a Decorators");
        }

        /// <summary>
        /// Test the property 'Container'
        /// </summary>
        [Test]
        public void ContainerTest()
        {
            // TODO unit test for the property 'Container'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'File'
        /// </summary>
        [Test]
        public void FileTest()
        {
            // TODO unit test for the property 'File'
        }
        /// <summary>
        /// Test the property 'Filesystem'
        /// </summary>
        [Test]
        public void FilesystemTest()
        {
            // TODO unit test for the property 'Filesystem'
        }
        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Parent'
        /// </summary>
        [Test]
        public void ParentTest()
        {
            // TODO unit test for the property 'Parent'
        }
        /// <summary>
        /// Test the property 'Preview'
        /// </summary>
        [Test]
        public void PreviewTest()
        {
            // TODO unit test for the property 'Preview'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Version'
        /// </summary>
        [Test]
        public void VersionTest()
        {
            // TODO unit test for the property 'Version'
        }

    }

}
