/* 
 * Xillio Engine
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Sphereon.SDK.Xillio.Engine.Api;
using Sphereon.SDK.Xillio.Engine.Model;
using Sphereon.SDK.Xillio.Engine.Client;
using System.Reflection;

namespace Sphereon.SDK.Xillio.Engine.Test
{
    /// <summary>
    ///  Class for testing NameDecorator
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NameDecoratorTests
    {
        // TODO uncomment below to declare an instance variable for NameDecorator
        //private NameDecorator instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NameDecorator
            //instance = new NameDecorator();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NameDecorator
        /// </summary>
        [Test]
        public void NameDecoratorInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NameDecorator
            //Assert.IsInstanceOfType<NameDecorator> (instance, "variable 'instance' is a NameDecorator");
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'SystemName'
        /// </summary>
        [Test]
        public void SystemNameTest()
        {
            // TODO unit test for the property 'SystemName'
        }

    }

}
