/**
 * Xillio Engine
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.xillio.engine.api;

import com.sphereon.sdk.xillio.engine.handler.ApiException;
import com.sphereon.sdk.xillio.engine.model.EntityResponse;
import com.sphereon.sdk.xillio.engine.model.ErrorResponse;
import java.io.File;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AllApi
 */
public class AllApiTest {

    private final AllApi api = new AllApi();

    
    /**
     * Create a new Entity
     *
     * Create a new Entity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createEntityTest() throws ApiException {
        String configurationId = null;
        String path = null;
        List<String> scope = null;
        String include = null;
        String exclude = null;
        String entity = null;
        String contents = null;
        // EntityResponse response = api.createEntity(configurationId, path, scope, include, exclude, entity, contents);

        // TODO: test validations
    }
    
    /**
     * Delete an existing Entity
     *
     * Delete an existing Entity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteEntityTest() throws ApiException {
        String configurationId = null;
        String path = null;
        // api.deleteEntity(configurationId, path);

        // TODO: test validations
    }
    
    /**
     * Download an Entity\&quot;s Binary Content
     *
     * Download an Entity\&quot;s Binary Content
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContentTest() throws ApiException {
        String configurationId = null;
        String path = null;
        // File response = api.getContent(configurationId, path);

        // TODO: test validations
    }
    
    /**
     * Get an Entity
     *
     * Get an Entity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getEntityTest() throws ApiException {
        String configurationId = null;
        String path = null;
        List<String> scope = null;
        String include = null;
        String exclude = null;
        // EntityResponse response = api.getEntity(configurationId, path, scope, include, exclude);

        // TODO: test validations
    }
    
    /**
     * List Available Entities/Repositories
     *
     * List Available Entities/Repositories
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listEntitiesTest() throws ApiException {
        List<String> scope = null;
        String include = null;
        String exclude = null;
        // EntityResponse response = api.listEntities(scope, include, exclude);

        // TODO: test validations
    }
    
    /**
     * Replaces an Entity\&quot;s Binary Content
     *
     * Replaces an Entity\&quot;s Binary Content
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateContentTest() throws ApiException {
        String configurationId = null;
        String path = null;
        // api.updateContent(configurationId, path);

        // TODO: test validations
    }
    
    /**
     * Update an existing Entity
     *
     * Update an existing Entity
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateEntityTest() throws ApiException {
        String configurationId = null;
        String path = null;
        List<String> scope = null;
        String include = null;
        String exclude = null;
        EntityResponse entity = null;
        // EntityResponse response = api.updateEntity(configurationId, path, scope, include, exclude, entity);

        // TODO: test validations
    }
    
}
