/**
 * Xillio Engine
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.xillio.engine.api;

import com.sphereon.sdk.xillio.engine.handler.ApiException;
import java.io.File;
import com.sphereon.sdk.xillio.engine.model.ErrorResponse;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContentApi
 */
public class ContentApiTest {

    private final ContentApi api = new ContentApi();

    
    /**
     * Download an Entity\&quot;s Binary Content
     *
     * Download an Entity\&quot;s Binary Content
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getContentTest() throws ApiException {
        String configurationId = null;
        String path = null;
        // File response = api.getContent(configurationId, path);

        // TODO: test validations
    }
    
    /**
     * Replaces an Entity\&quot;s Binary Content
     *
     * Replaces an Entity\&quot;s Binary Content
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateContentTest() throws ApiException {
        String configurationId = null;
        String path = null;
        // api.updateContent(configurationId, path);

        // TODO: test validations
    }
    
}
