/**
 * Xillio Engine
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.xillio.engine.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.sphereon.sdk.xillio.engine.model.ContainerDecorator;
import com.sphereon.sdk.xillio.engine.model.CreatedDecorator;
import com.sphereon.sdk.xillio.engine.model.DescriptionDecorator;
import com.sphereon.sdk.xillio.engine.model.FileDecorator;
import com.sphereon.sdk.xillio.engine.model.FileSystemDecorator;
import com.sphereon.sdk.xillio.engine.model.HashDecorator;
import com.sphereon.sdk.xillio.engine.model.MimeTypeDecorator;
import com.sphereon.sdk.xillio.engine.model.ModifiedDecorator;
import com.sphereon.sdk.xillio.engine.model.NameDecorator;
import com.sphereon.sdk.xillio.engine.model.ParentDecorator;
import com.sphereon.sdk.xillio.engine.model.PreviewDecorator;
import com.sphereon.sdk.xillio.engine.model.PropertiesDecorator;
import com.sphereon.sdk.xillio.engine.model.VersionDecorator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Decorators
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T22:58:01.852+01:00")
public class Decorators   {
  @SerializedName("container")
  private ContainerDecorator container = null;

  @SerializedName("created")
  private CreatedDecorator created = null;

  @SerializedName("description")
  private DescriptionDecorator description = null;

  @SerializedName("file")
  private FileDecorator file = null;

  @SerializedName("filesystem")
  private FileSystemDecorator filesystem = null;

  @SerializedName("hash")
  private HashDecorator hash = null;

  @SerializedName("mimeType")
  private MimeTypeDecorator mimeType = null;

  @SerializedName("modified")
  private ModifiedDecorator modified = null;

  @SerializedName("name")
  private NameDecorator name = null;

  @SerializedName("parent")
  private ParentDecorator parent = null;

  @SerializedName("preview")
  private PreviewDecorator preview = null;

  @SerializedName("properties")
  private PropertiesDecorator properties = null;

  @SerializedName("version")
  private VersionDecorator version = null;

  public Decorators container(ContainerDecorator container) {
    this.container = container;
    return this;
  }

   /**
   * Get container
   * @return container
  **/
  @ApiModelProperty(example = "null", value = "")
  public ContainerDecorator getContainer() {
    return container;
  }

  public void setContainer(ContainerDecorator container) {
    this.container = container;
  }

  public Decorators created(CreatedDecorator created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(example = "null", value = "")
  public CreatedDecorator getCreated() {
    return created;
  }

  public void setCreated(CreatedDecorator created) {
    this.created = created;
  }

  public Decorators description(DescriptionDecorator description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public DescriptionDecorator getDescription() {
    return description;
  }

  public void setDescription(DescriptionDecorator description) {
    this.description = description;
  }

  public Decorators file(FileDecorator file) {
    this.file = file;
    return this;
  }

   /**
   * Get file
   * @return file
  **/
  @ApiModelProperty(example = "null", value = "")
  public FileDecorator getFile() {
    return file;
  }

  public void setFile(FileDecorator file) {
    this.file = file;
  }

  public Decorators filesystem(FileSystemDecorator filesystem) {
    this.filesystem = filesystem;
    return this;
  }

   /**
   * Get filesystem
   * @return filesystem
  **/
  @ApiModelProperty(example = "null", value = "")
  public FileSystemDecorator getFilesystem() {
    return filesystem;
  }

  public void setFilesystem(FileSystemDecorator filesystem) {
    this.filesystem = filesystem;
  }

  public Decorators hash(HashDecorator hash) {
    this.hash = hash;
    return this;
  }

   /**
   * Get hash
   * @return hash
  **/
  @ApiModelProperty(example = "null", value = "")
  public HashDecorator getHash() {
    return hash;
  }

  public void setHash(HashDecorator hash) {
    this.hash = hash;
  }

  public Decorators mimeType(MimeTypeDecorator mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
   * Get mimeType
   * @return mimeType
  **/
  @ApiModelProperty(example = "null", value = "")
  public MimeTypeDecorator getMimeType() {
    return mimeType;
  }

  public void setMimeType(MimeTypeDecorator mimeType) {
    this.mimeType = mimeType;
  }

  public Decorators modified(ModifiedDecorator modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(example = "null", value = "")
  public ModifiedDecorator getModified() {
    return modified;
  }

  public void setModified(ModifiedDecorator modified) {
    this.modified = modified;
  }

  public Decorators name(NameDecorator name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "null", value = "")
  public NameDecorator getName() {
    return name;
  }

  public void setName(NameDecorator name) {
    this.name = name;
  }

  public Decorators parent(ParentDecorator parent) {
    this.parent = parent;
    return this;
  }

   /**
   * Get parent
   * @return parent
  **/
  @ApiModelProperty(example = "null", value = "")
  public ParentDecorator getParent() {
    return parent;
  }

  public void setParent(ParentDecorator parent) {
    this.parent = parent;
  }

  public Decorators preview(PreviewDecorator preview) {
    this.preview = preview;
    return this;
  }

   /**
   * Get preview
   * @return preview
  **/
  @ApiModelProperty(example = "null", value = "")
  public PreviewDecorator getPreview() {
    return preview;
  }

  public void setPreview(PreviewDecorator preview) {
    this.preview = preview;
  }

  public Decorators properties(PropertiesDecorator properties) {
    this.properties = properties;
    return this;
  }

   /**
   * Get properties
   * @return properties
  **/
  @ApiModelProperty(example = "null", value = "")
  public PropertiesDecorator getProperties() {
    return properties;
  }

  public void setProperties(PropertiesDecorator properties) {
    this.properties = properties;
  }

  public Decorators version(VersionDecorator version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(example = "null", value = "")
  public VersionDecorator getVersion() {
    return version;
  }

  public void setVersion(VersionDecorator version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Decorators decorators = (Decorators) o;
    return Objects.equals(this.container, decorators.container) &&
        Objects.equals(this.created, decorators.created) &&
        Objects.equals(this.description, decorators.description) &&
        Objects.equals(this.file, decorators.file) &&
        Objects.equals(this.filesystem, decorators.filesystem) &&
        Objects.equals(this.hash, decorators.hash) &&
        Objects.equals(this.mimeType, decorators.mimeType) &&
        Objects.equals(this.modified, decorators.modified) &&
        Objects.equals(this.name, decorators.name) &&
        Objects.equals(this.parent, decorators.parent) &&
        Objects.equals(this.preview, decorators.preview) &&
        Objects.equals(this.properties, decorators.properties) &&
        Objects.equals(this.version, decorators.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(container, created, description, file, filesystem, hash, mimeType, modified, name, parent, preview, properties, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Decorators {\n");
    
    sb.append("    container: ").append(toIndentedString(container)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    file: ").append(toIndentedString(file)).append("\n");
    sb.append("    filesystem: ").append(toIndentedString(filesystem)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("    preview: ").append(toIndentedString(preview)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

