/**
 * Xillio Engine
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.xillio.engine.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import com.sphereon.sdk.xillio.engine.model.Decorators;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * UDM Entity
 */
@ApiModel(description = "UDM Entity")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T22:58:01.852+01:00")
public class Entity   {
  @SerializedName("id")
  private String id = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("xdip")
  private String xdip = null;

  @SerializedName("original")
  private Decorators original = null;

  @SerializedName("modified")
  private Decorators modified = null;

  public Entity id(String id) {
    this.id = id;
    return this;
  }

   /**
   * An URL that points to the entity.
   * @return id
  **/
  @ApiModelProperty(example = "null", required = true, value = "An URL that points to the entity.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Entity kind(String kind) {
    this.kind = kind;
    return this;
  }

   /**
   * A simple content type string that describes the best match for the entity.
   * @return kind
  **/
  @ApiModelProperty(example = "null", value = "A simple content type string that describes the best match for the entity.")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public Entity xdip(String xdip) {
    this.xdip = xdip;
    return this;
  }

   /**
   * Xdip
   * @return xdip
  **/
  @ApiModelProperty(example = "null", value = "Xdip")
  public String getXdip() {
    return xdip;
  }

  public void setXdip(String xdip) {
    this.xdip = xdip;
  }

  public Entity original(Decorators original) {
    this.original = original;
    return this;
  }

   /**
   * Get original
   * @return original
  **/
  @ApiModelProperty(example = "null", value = "")
  public Decorators getOriginal() {
    return original;
  }

  public void setOriginal(Decorators original) {
    this.original = original;
  }

  public Entity modified(Decorators modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Decorators getModified() {
    return modified;
  }

  public void setModified(Decorators modified) {
    this.modified = modified;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entity entity = (Entity) o;
    return Objects.equals(this.id, entity.id) &&
        Objects.equals(this.kind, entity.kind) &&
        Objects.equals(this.xdip, entity.xdip) &&
        Objects.equals(this.original, entity.original) &&
        Objects.equals(this.modified, entity.modified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, kind, xdip, original, modified);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entity {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    xdip: ").append(toIndentedString(xdip)).append("\n");
    sb.append("    original: ").append(toIndentedString(original)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

