/**
 * Xillio Engine
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.sphereon.sdk.xillio.engine.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;


/**
 * The modified decorator signifies when an entity was last modified.
 */
@ApiModel(description = "The modified decorator signifies when an entity was last modified.")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T22:58:01.852+01:00")
public class ModifiedDecorator   {
  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("by")
  private String by = null;

  public ModifiedDecorator date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * The last modification date of the entity.
   * @return date
  **/
  @ApiModelProperty(example = "null", required = true, value = "The last modification date of the entity.")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public ModifiedDecorator by(String by) {
    this.by = by;
    return this;
  }

   /**
   * The name of the user or entity that last modified this entity.
   * @return by
  **/
  @ApiModelProperty(example = "null", value = "The name of the user or entity that last modified this entity.")
  public String getBy() {
    return by;
  }

  public void setBy(String by) {
    this.by = by;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModifiedDecorator modifiedDecorator = (ModifiedDecorator) o;
    return Objects.equals(this.date, modifiedDecorator.date) &&
        Objects.equals(this.by, modifiedDecorator.by);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, by);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModifiedDecorator {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    by: ").append(toIndentedString(by)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

