/*
 * Xillio Engine
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.jclouds.xillio.engine.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

/**
 * The created decorator signifies when an entity was created.
 */
@ApiModel(description = "The created decorator signifies when an entity was created.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-30T06:23:19.976+01:00")
public class CreatedDecorator {
  @SerializedName("date")
  private OffsetDateTime date = null;

  @SerializedName("by")
  private String by = null;

  public CreatedDecorator date(OffsetDateTime date) {
    this.date = date;
    return this;
  }

   /**
   * The creation date of the entity.
   * @return date
  **/
  @ApiModelProperty(required = true, value = "The creation date of the entity.")
  public OffsetDateTime getDate() {
    return date;
  }

  public void setDate(OffsetDateTime date) {
    this.date = date;
  }

  public CreatedDecorator by(String by) {
    this.by = by;
    return this;
  }

   /**
   * The name of the user or entity that created this entity.
   * @return by
  **/
  @ApiModelProperty(value = "The name of the user or entity that created this entity.")
  public String getBy() {
    return by;
  }

  public void setBy(String by) {
    this.by = by;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreatedDecorator createdDecorator = (CreatedDecorator) o;
    return Objects.equals(this.date, createdDecorator.date) &&
        Objects.equals(this.by, createdDecorator.by);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, by);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreatedDecorator {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    by: ").append(toIndentedString(by)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

