/*
 * Xillio Engine
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.jclouds.xillio.engine.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The description decorator provides a small excerpt or description for an entity. This is generally used as a preview message or subtitle.
 */
@ApiModel(description = "The description decorator provides a small excerpt or description for an entity. This is generally used as a preview message or subtitle.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-30T06:23:19.976+01:00")
public class DescriptionDecorator {
  @SerializedName("short")
  private String _short = null;

  public DescriptionDecorator _short(String _short) {
    this._short = _short;
    return this;
  }

   /**
   * A short extract or subtitle of the entity.
   * @return _short
  **/
  @ApiModelProperty(required = true, value = "A short extract or subtitle of the entity.")
  public String getShort() {
    return _short;
  }

  public void setShort(String _short) {
    this._short = _short;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescriptionDecorator descriptionDecorator = (DescriptionDecorator) o;
    return Objects.equals(this._short, descriptionDecorator._short);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_short);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescriptionDecorator {\n");
    
    sb.append("    _short: ").append(toIndentedString(_short)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

