/*
 * Xillio Engine
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.jclouds.xillio.engine.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * The file decorator contains various pieces of information related to files on a file system.
 */
@ApiModel(description = "The file decorator contains various pieces of information related to files on a file system.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-21T22:36:36.417+01:00")
public class FileDecorator {
  @SerializedName("extension")
  private String extension = null;

  @SerializedName("rawExtension")
  private String rawExtension = null;

  @SerializedName("size")
  private BigDecimal size = null;

  public FileDecorator extension(String extension) {
    this.extension = extension;
    return this;
  }

   /**
   * The (optionally cleaned) extension of the file.
   * @return extension
  **/
  @ApiModelProperty(required = true, value = "The (optionally cleaned) extension of the file.")
  public String getExtension() {
    return extension;
  }

  public void setExtension(String extension) {
    this.extension = extension;
  }

  public FileDecorator rawExtension(String rawExtension) {
    this.rawExtension = rawExtension;
    return this;
  }

   /**
   * The extension of the file as found on the filesystem.
   * @return rawExtension
  **/
  @ApiModelProperty(required = true, value = "The extension of the file as found on the filesystem.")
  public String getRawExtension() {
    return rawExtension;
  }

  public void setRawExtension(String rawExtension) {
    this.rawExtension = rawExtension;
  }

  public FileDecorator size(BigDecimal size) {
    this.size = size;
    return this;
  }

   /**
   * The byte-size of the file in kilobytes.
   * @return size
  **/
  @ApiModelProperty(required = true, value = "The byte-size of the file in kilobytes.")
  public BigDecimal getSize() {
    return size;
  }

  public void setSize(BigDecimal size) {
    this.size = size;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileDecorator fileDecorator = (FileDecorator) o;
    return Objects.equals(this.extension, fileDecorator.extension) &&
        Objects.equals(this.rawExtension, fileDecorator.rawExtension) &&
        Objects.equals(this.size, fileDecorator.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(extension, rawExtension, size);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileDecorator {\n");
    
    sb.append("    extension: ").append(toIndentedString(extension)).append("\n");
    sb.append("    rawExtension: ").append(toIndentedString(rawExtension)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

