/*
 * Xillio Engine
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.jclouds.xillio.engine.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The hash decorator contains one or more types of hashes corresponding to the entity.
 */
@ApiModel(description = "The hash decorator contains one or more types of hashes corresponding to the entity.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-30T06:23:19.976+01:00")
public class HashDecorator {
  @SerializedName("md5")
  private String md5 = null;

  @SerializedName("sha1")
  private String sha1 = null;

  @SerializedName("sha256")
  private String sha256 = null;

  public HashDecorator md5(String md5) {
    this.md5 = md5;
    return this;
  }

   /**
   * The md5 hash of the entity\&quot;s binary contents.
   * @return md5
  **/
  @ApiModelProperty(value = "The md5 hash of the entity\"s binary contents.")
  public String getMd5() {
    return md5;
  }

  public void setMd5(String md5) {
    this.md5 = md5;
  }

  public HashDecorator sha1(String sha1) {
    this.sha1 = sha1;
    return this;
  }

   /**
   * The sha1 hash of the entity\&quot;s binary contents.
   * @return sha1
  **/
  @ApiModelProperty(value = "The sha1 hash of the entity\"s binary contents.")
  public String getSha1() {
    return sha1;
  }

  public void setSha1(String sha1) {
    this.sha1 = sha1;
  }

  public HashDecorator sha256(String sha256) {
    this.sha256 = sha256;
    return this;
  }

   /**
   * The sha256 hash of the entity\&quot;s binary contents.
   * @return sha256
  **/
  @ApiModelProperty(value = "The sha256 hash of the entity\"s binary contents.")
  public String getSha256() {
    return sha256;
  }

  public void setSha256(String sha256) {
    this.sha256 = sha256;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HashDecorator hashDecorator = (HashDecorator) o;
    return Objects.equals(this.md5, hashDecorator.md5) &&
        Objects.equals(this.sha1, hashDecorator.sha1) &&
        Objects.equals(this.sha256, hashDecorator.sha256);
  }

  @Override
  public int hashCode() {
    return Objects.hash(md5, sha1, sha256);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HashDecorator {\n");
    
    sb.append("    md5: ").append(toIndentedString(md5)).append("\n");
    sb.append("    sha1: ").append(toIndentedString(sha1)).append("\n");
    sb.append("    sha256: ").append(toIndentedString(sha256)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

