/*
 * Xillio Engine
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.jclouds.xillio.engine.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * The name decorator represents both a technical name and a human readable name for an entity. This could be anything from the title of a web page to the filename of a document.
 */
@ApiModel(description = "The name decorator represents both a technical name and a human readable name for an entity. This could be anything from the title of a web page to the filename of a document.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-30T06:23:19.976+01:00")
public class NameDecorator {
  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("systemName")
  private String systemName = null;

  public NameDecorator displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The human readable name of the entity.
   * @return displayName
  **/
  @ApiModelProperty(required = true, value = "The human readable name of the entity.")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public NameDecorator systemName(String systemName) {
    this.systemName = systemName;
    return this;
  }

   /**
   * The technical name of the entity.
   * @return systemName
  **/
  @ApiModelProperty(required = true, value = "The technical name of the entity.")
  public String getSystemName() {
    return systemName;
  }

  public void setSystemName(String systemName) {
    this.systemName = systemName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NameDecorator nameDecorator = (NameDecorator) o;
    return Objects.equals(this.displayName, nameDecorator.displayName) &&
        Objects.equals(this.systemName, nameDecorator.systemName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayName, systemName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NameDecorator {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    systemName: ").append(toIndentedString(systemName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

